export const GET_ALL_TRADES = 'GET_ALL_TRADES';
export const RECEIVE_TRADES = 'RECEIVE_TRADES';
export const GET_TRADES_COLUMNS = 'GET_TRADES_COLUMNS';
export const ADD_NEW_TRADE = 'ADD_NEW_TRADE';
export const ADD_NEW_TRADE_SUCCESS = 'ADD_NEW_TRADE_SUCCESS';
