const actionTypes = {
        GET_ALL_TRADES: 'GET_ALL_TRADES',
        RECEIVE_TRADES: 'RECEIVE_TRADES',
        GET_TRADES_COLUMNS: 'GET_TRADES_COLUMNS',
        ADD_NEW_TRADE: 'ADD_NEW_TRADE',
        ADD_NEW_TRADE_SUCCESS: 'ADD_NEW_TRADE_SUCCESS',
        ADD_NEW_TRADE_FAIL: 'ADD_NEW_TRADE_FAIL',
        UPDATE_TRADE: 'UPDATE_TRADE',
        UPDATE_TRADE_SUCCESS: 'UPDATE_TRADE_SUCCESS',
        DELETE_TRADE: 'DELETE_TRADE',
        DELETE_TRADE_SUCCESS: 'DELETE_TRADE_SUCCESS'
}

export default actionTypes;
